yookan_todo_proj/yookan_todo/yookan_todo/todo/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = 'todo'
urlpatterns = [
    # path('login/', auth.views.login, {'template_name': 'login.html'}),#views.login, name='login'),
    # path('logout/', auth.views.logout, {'next_page': '/login/'}),

    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='/login/'), name='logout'),

    path('dashboard/', views.dashboard, name='dashboard'),

    path('tasks/', views.tasks, name='tasks'),
    path('task/', views.task_detail, name='add_task'),
    path('task/<int:task_id>/', views.task_detail, name='task_detail'),

    path('categories/', views.categories, name='categories'),
    path('category/', views.category_detail, name='add_category'),
    path('category/<int:category_id>/', views.category_detail, name='category_detail'),

    path('tasklists/', views.task_lists, name='task_lists'),
    path('tasklist/', views.task_list_detail, name='add_task_list'),
    path('tasklist/<int:task_list_id>/detail', views.task_list_detail, name='task_list_detail'),
]

yookan_todo_proj/yookan_todo/yookan_todo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # path('accounts/', include('django.contrib.auth.urls')),
	path('', include('yookan_todo.todo.urls')),
    path('api/', include('yookan_todo.todo.api_urls')),
    path('admin/', admin.site.urls),
]

yookan_todo_proj/yookan_todo/yookan_todo/todo/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime


class Category(models.Model):
    created_on = models.DateTimeField(auto_now=True)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=256)

    @staticmethod
    def get_all_categories_for_user(creator):
        return Category.objects.filter(creator=creator).order_by('-created_on')

    def __str__(self):
        return self.name


class TaskList(models.Model):
    created_on = models.DateTimeField(auto_now=True)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=256)

    @staticmethod
    def get_all_task_list_for_user(creator):
        return TaskList.objects.filter(creator=creator).order_by('-created_on')

    def __str__(self):
        return self.name


class Task(models.Model):
    STATUS_CHOICES = (
        ('P', 'Pending'),
        ('I', 'In Progress'),
        ('C', 'Complete'),
    )
    created_on = models.DateTimeField(auto_now=True)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=256)
    description = models.TextField()
    target_date = models.DateField(default=datetime.date(datetime.now()))
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='P') 
    category = models.ForeignKey(
        Category, null=True, blank=True, related_name='tasks', on_delete=models.CASCADE
    )
    task_list = models.ForeignKey(
        TaskList, null=True, blank=True, related_name='tasks', on_delete=models.CASCADE
    )

    @staticmethod
    def get_all_tasks_for_user(creator):
        return Task.objects.filter(creator=creator).order_by('-created_on')

    @staticmethod
    def get_all_tasks_due_on(creator, date):
        return Task.objects.filter(
            creator=creator,
            target_date=date,
        ).order_by('-created_on')

    def __str__(self):
        return self.title

yookan_todo_proj/yookan_todo/yookan_todo/todo/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Category, Task, TaskList


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        exclude = ['creator', 'created_on']


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        exclude = ['creator', 'created_on']


class TaskListForm(forms.ModelForm):
    class Meta:
        model = TaskList
        exclude = ['creator', 'created_on']

yookan_todo_proj/yookan_todo/yookan_todo/todo/views.py
from datetime import datetime

from django.contrib.auth import login, logout, authenticate
from django.shortcuts import render, get_object_or_404, redirect

from .models import Category, Task, TaskList
from .forms import CategoryForm, TaskForm, TaskListForm


def dashboard(request):
    user = request.user
    latest_due_tasks = Task.get_all_tasks_due_on(
        user,
        datetime.date(datetime.now()),
    )
    completed_task_count = Task.objects.filter(status='C').count()
    in_progress_task_count = Task.objects.filter(status='I').count()
    pending_task_count = Task.objects.filter(status='P').count()
    context = {
        'completed_task_count': completed_task_count,
        'in_progress_task_count': in_progress_task_count,
        'pending_task_count': pending_task_count,
        'latest_due_tasks': latest_due_tasks,
    }

    return render(request, 'dashboard.html', context)


def tasks(request):
    user = request.user
    tasks = Task.get_all_tasks_for_user(user)

    return render(request, 'tasks.html', {'tasks': tasks})


def task_detail(request, task_id=None):
    user = request.user
    if task_id:
        task = get_object_or_404(Task, pk=task_id, creator=user)
    else:
        task = None

    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            if task is None:
                form.instance.creator = user
            form.save()
            task = form.instance
        return redirect('todo:task_detail', task_id=task.id)
    else:
        form = TaskForm(instance=task)

    return render(request, 'task.html', {'form': form,})


def task_lists(request):
    user= request.user
    task_lists = TaskList.get_all_task_list_for_user(user)

    return render(request, 'task_lists.html', {'task_lists': task_lists})


def task_list_detail(request, task_list_id=None):
    user = request.user
    if task_list_id:
        task_list = get_object_or_404(TaskList, pk=task_list_id, creator=user)
    else:
        task_list = None

    if request.method == 'POST':
        form = TaskListForm(request.POST, instance=task_list)
        if form.is_valid():
            if task_list is None:
                form.instance.creator = user
            form.save()
            task_list = form.instance
        return redirect('todo:task_list_detail', task_list_id=task_list.id)
    else:
        form = TaskListForm(instance=task_list)

    return render(request, 'task_list_detail.html', {'form': form,})

def categories(request):
    user= request.user
    categories = Category.get_all_categories_for_user(user)

    return render(request, 'dashboard.html', {'categories': categories})


def category_detail(request, category_id=None):
    user = request.user
    if category_id:
        category = get_object_or_404(Category, pk=category_id, creator=user)
    else:
        category = None

    if request.method == 'POST':
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            if category is None:
                form.instance.creator = user
            form.save()
            category = form.instance
        return redirect('todo:category_detail', category_id=category.id)
    else:
        form = CategoryForm(instance=category)

    return render(request, 'category.html', {'form': form,})

yookan_todo_proj/yookan_todo/yookan_todo/todo/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>YooKan ToDo</title>
  </head>

  <body>
    {% block nav %}
    {% endblock %}

    {% block content %}
    {% endblock %}
  </body>
</html>

yookan_todo_proj/yookan_todo/yookan_todo/todo/templates/dashboard.html
{% extends "dashboard_base.html" %}

{% block content %}
<p>
No.Of Completed Tasks: {{ completed_task_count }}
<br><br>No.Of In Progress Tasks: {{ in_progress_task_count }}
<br><br>No.Of Pending Tasks: {{ pending_task_count }}
</p>
<p>
Tasks:
</p>
<p>
  <ol>
    {% for task in latest_due_tasks %}
      <li><a href="{% url 'todo:task_detail' task.id %}">{{ task.title }}</a>
    {% endfor %}
  </ol>
</p>
{% endblock %}

yookan_todo_proj/yookan_todo/yookan_todo/todo/templates/dashboard_base.html
{% extends "base.html" %}
{% block nav %}
<p>
	{% if user.is_authenticated %}
		<a href="{% url 'todo:dashboard' %}">Dashboard</a> |
		<a href="{% url 'todo:tasks' %}">Tasks</a> |
		<a href="{% url 'todo:task_lists' %}">Task Lists</a> |
		<a href="{% url 'todo:categories' %}">Categories</a> |

		<a href="{% url 'todo:add_task' %}">New Task</a> |
		<a href="{% url 'todo:add_task_list' %}">New List</a> |
		<a href="{% url 'todo:add_category' %}">New Category</a> |

		<a href="{% url 'todo:logout' %}">Logout</a>
	{% endif %}
	
</p>
{% endblock %}

{% block content %}
{% endblock %}

yookan_todo_proj/yookan_todo/yookan_todo/todo/templates/login.html
{% extends "base.html" %}

{% block content %}
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Login</button>
</form>
{% endblock %}

yookan_todo_proj/yookan_todo/yookan_todo/todo/templates/task.html
{% extends "dashboard_base.html" %}

{% block content %}
</p>
<p>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Save</button>
    </form>
</p>
{% endblock %}

yookan_todo_proj/yookan_todo/yookan_todo/todo/templates/task_list.html
{% extends "dashboard_base.html" %}

{% block content %}
Task List: {{ task_list.name }}:
</p>
<p>
  <ol>
  	{{ task_list }}
    {% for task in task_list.tasks %}
      <li><a href="{% url 'todo:task_detail' task.id %}">{{ task.title }}</a>
    {% endfor %}
  </ol>
</p>
{% endblock %}

yookan_todo_proj/yookan_todo/yookan_todo/todo/templates/task_list_detail.html
{% extends "dashboard_base.html" %}

{% block content %}
</p>
<p>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Save</button>
    </form>
</p>
<p>
  Tasks:
  <ol>
    {% for task in form.instance.tasks.all %}
      <li><a href="{% url 'todo:task_detail' task.id %}">{{ task.title }}</a>
    {% endfor %}
  </ol>
</p>
{% endblock %}

yookan_todo_proj/yookan_todo/yookan_todo/todo/templates/task_lists.html
{% extends "dashboard_base.html" %}

{% block content %}
All Task Lists:
</p>
<p>
  <ol>
    {% for list in task_lists %}
      <li><a href="{% url 'todo:task_list_detail' list.id %}">{{ list.name }}</a>
    {% endfor %}
  </ol>
</p>
{% endblock %}

yookan_todo_proj/yookan_todo/yookan_todo/todo/templates/tasks.html
{% extends "dashboard_base.html" %}

{% block content %}
All Tasks:
</p>
<p>
  <ol>
    {% for task in tasks %}
      <li><a href="{% url 'todo:task_detail' task.id %}">{{ task.title }}</a>
    {% endfor %}
  </ol>
</p>
{% endblock %}